### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by rincont** [mit-eicu/eicu-website#30] opened 2017-02-12 17:43 UTC
I am starting to work on this. Question: Do we need breif definitions or just acronyms and terms e.g. APACHE: acute physiology age chronic health evaluation 
APS: acute physiology score 
etc....

**Comment by alistairewj** [comment] 2017-02-12 17:57
Acronyms and terms is a good start!

**Comment by tompollard** [comment] 2017-02-13 23:00
Duplicate of https://github.com/mit-eicu/eicu-website/issues/26

**Closed by tompollard** 2017-02-13 23:00 UTC
